CROPS_USED = [
    "rice",
    "maize",
    "banana",
    "mango",
    "apple",
    "jute",
    "papaya",
    "lentil",
    "orange",
    "cotton",
]

GRID_WIDTH = 4

MODEL_ALPHA = 100
MODEL_GOLDUNIT = 10
SPEED = 1400

MONTHS = [
    "Baisakh",
    "Jestha",
    "Asar",
    "Shrawan",
    "Bhadra",
    "Ashwin",
    "Kartik",
    "Mangsir",
    "Poush",
    "Magh",
    "Falgun",
    "Chaitra",
]

REGIONS = {
    "Terai": {
        "temperature": 30.0,
        "humidity": 80.0,
        "rainfall": 150.0,
        "moisture": 60.0,
        "desc": "Hot, humid plains of southern Nepal; major rice, maize, jute, sugarcane, cotton belt.",
    },
    "Hilly": {
        "temperature": 20.0,
        "humidity": 60.0,
        "rainfall": 100.0,
        "moisture": 45.0,
        "desc": "Mid‑hills with moderate climate; suitable for maize, millet, vegetables, citrus, lentil.",
    },
    "Himalayan": {
        "temperature": 5.0,
        "humidity": 40.0,
        "rainfall": 50.0,
        "moisture": 30.0,
        "desc": "High mountains; cool climate; apples, barley, potatoes, off‑season vegetables.",
    },
}

CROPS = {
    "Rice": {
        "cost": {"Terai": 150, "Hilly": 180, "Himalayan": 220},
        "days": 12,
        "harvest_gold": 220,
        "ideal": {
            "moisture": 80,
            "temperature": 24,
            "n": 80,
            "p": 48,
            "k": 40,
            "humidity": 82,
            "ph": 6,
            "rainfall": 236,
        },
    },
    "Maize": {
        "cost": {"Terai": 120, "Hilly": 140, "Himalayan": 170},
        "days": 10,
        "harvest_gold": 190,
        "ideal": {
            "moisture": 55,
            "temperature": 22,
            "n": 78,
            "p": 48,
            "k": 20,
            "humidity": 65,
            "ph": 6,
            "rainfall": 85,
        },
    },
    "Banana": {
        "cost": {"Terai": 200, "Hilly": 220, "Himalayan": 260},
        "days": 18,
        "harvest_gold": 320,
        "ideal": {
            "moisture": 70,
            "temperature": 27,
            "n": 100,
            "p": 82,
            "k": 50,
            "humidity": 80,
            "ph": 6,
            "rainfall": 105,
        },
    },
    "Mango": {
        "cost": {"Terai": 220, "Hilly": 240, "Himalayan": 280},
        "days": 18,
        "harvest_gold": 340,
        "ideal": {
            "moisture": 60,
            "temperature": 31,
            "n": 20,
            "p": 27,
            "k": 30,
            "humidity": 50,
            "ph": 6,
            "rainfall": 95,
        },
    },
    "Apple": {
        "cost": {"Terai": 260, "Hilly": 240, "Himalayan": 220},
        "days": 20,
        "harvest_gold": 360,
        "ideal": {
            "moisture": 50,
            "temperature": 23,
            "n": 21,
            "p": 134,
            "k": 200,
            "humidity": 92,
            "ph": 6,
            "rainfall": 113,
        },
    },
    "Jute": {
        "cost": {"Terai": 140, "Hilly": 170, "Himalayan": 200},
        "days": 14,
        "harvest_gold": 230,
        "ideal": {
            "moisture": 65,
            "temperature": 25,
            "n": 78,
            "p": 47,
            "k": 40,
            "humidity": 80,
            "ph": 7,
            "rainfall": 175,
        },
    },
    "Papaya": {
        "cost": {"Terai": 190, "Hilly": 210, "Himalayan": 250},
        "days": 16,
        "harvest_gold": 310,
        "ideal": {
            "moisture": 65,
            "temperature": 34,
            "n": 50,
            "p": 59,
            "k": 50,
            "humidity": 92,
            "ph": 7,
            "rainfall": 143,
        },
    },
    "Lentil": {
        "cost": {"Terai": 110, "Hilly": 120, "Himalayan": 150},
        "days": 11,
        "harvest_gold": 200,
        "ideal": {
            "moisture": 45,
            "temperature": 25,
            "n": 19,
            "p": 68,
            "k": 19,
            "humidity": 65,
            "ph": 7,
            "rainfall": 46,
        },
    },
    "Orange": {
        "cost": {"Terai": 210, "Hilly": 200, "Himalayan": 230},
        "days": 18,
        "harvest_gold": 330,
        "ideal": {
            "moisture": 55,
            "temperature": 23,
            "n": 20,
            "p": 17,
            "k": 10,
            "humidity": 92,
            "ph": 7,
            "rainfall": 110,
        },
    },
    "Cotton": {
        "cost": {"Terai": 160, "Hilly": 190, "Himalayan": 220},
        "days": 15,
        "harvest_gold": 240,
        "ideal": {
            "moisture": 55,
            "temperature": 24,
            "n": 118,
            "p": 46,
            "k": 20,
            "humidity": 80,
            "ph": 7,
            "rainfall": 80,
        },
    },
}


ACTIONS = {
    "plough": {
        "name": "Tractor Ploughing",
        "cost": {"Terai": 90, "Hilly": 110, "Himalayan": 130},
        "effect": {"moisture": -5},
        "desc": "Primary tillage using tractor or power tiller, common in Terai and accessible hills.",
        "duration": 3,
    },
    "irrigate": {
        "name": "Canal / Tube-well Irrigation",
        "cost": {"Terai": 70, "Hilly": 90, "Himalayan": 110},
        "effect": {"moisture": 20, "temperature": -1},
        "desc": "Flood or furrow irrigation from canal, river lift, or tube-well depending on region.",
        "duration": 3,
    },
    "fertilizer/chemical/nitrogen": {
        "name": "Urea (46% Nitrogen)",
        "cost": {"Terai": 60, "Hilly": 65, "Himalayan": 70},
        "effect": {"n": 30, "p": 0, "k": 0, "ph": -0.1},
        "desc": "Common nitrogen fertilizer used across Nepal to boost vegetative growth.",
        "duration": 2,
    },
    "fertilizer/chemical/phosphorus": {
        "name": "DAP (18-46-0)",
        "cost": {"Terai": 70, "Hilly": 75, "Himalayan": 80},
        "effect": {"n": 10, "p": 25, "k": 0, "ph": -0.05},
        "desc": "Diammonium phosphate, major source of phosphorus with some nitrogen.",
        "duration": 2,
    },
    "fertilizer/chemical/potassium": {
        "name": "MOP (0-0-60)",
        "cost": {"Terai": 65, "Hilly": 70, "Himalayan": 75},
        "effect": {"n": 0, "p": 0, "k": 25},
        "desc": "Muriate of potash, common potassium fertilizer for grain and fruit crops.",
        "duration": 2,
    },
    "fertilizer/organic/fym": {
        "name": "Farmyard Manure (FYM)",
        "cost": {"Terai": 50, "Hilly": 55, "Himalayan": 60},
        "effect": {"n": 5, "p": 5, "k": 5, "ph": 0.05},
        "desc": "Cattle/buffalo manure and compost, widely used in hill and mountain farms.",
        "duration": 3,
    },
    "mulch": {
        "name": "Mulching with Crop Residue",
        "cost": {"Terai": 40, "Hilly": 45, "Himalayan": 50},
        "effect": {"moisture": 10},
        "desc": "Use of rice straw, maize stover, or leaf litter to conserve soil moisture.",
        "duration": 3,
    },
    "harvest": {
        "name": "Harvest and Thresh",
        "cost": {"Terai": 100, "Hilly": 110, "Himalayan": 130},
        "effect": {},
        "desc": "Cutting, collecting, and threshing or packing produce for market.",
        "duration": 4,
    },
    "remove_crop": {
        "name": "Remove Crop",
        "cost": {"Terai": 20, "Hilly": 25, "Himalayan": 30},
        "effect": {},
        "desc": "Remove unwanted crops from the field.",
        "duration": 1,
    },
}
